### ISSUE TITLE
TODO list for Python 3.11 support

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/astroid#1516]
- [x] Re-enable `numpy` as a test dependency once they provide wheels for `3.11` > See #1517
- [x] Remove the `if: ${{ always() }}` line from the `coverage` CI jobs
- [ ] Handle PEP654 (https://github.com/PyCQA/pylint/issues/7703) #2028 
- [x] `FormattedValue.conversion` is a required field (instead of optional). This was an error in the Python documentation which was addressed recently. https://docs.python.org/3.11/library/ast.html#ast.FormattedValue https://github.com/python/cpython/pull/30467 > https://github.com/PyCQA/astroid/pull/2029
- [x] [Optional] We could add an enum for `FormattedValue.conversion`. The int values can be confusion on its own. > Decided not to.

**Comment by cdce8p** [comment]
Some recent AST changes:
* Add support for new `TryStar` node. Almost identical to the `ast.Try` node. We shouldn't use the old `TryExcept` / `TryFinally` structure though! It's probably better to look at #1389
https://docs.python.org/3.11/library/ast.html#ast.TryStar
https://github.com/python/cpython/pull/29581
* `FormattedValue.conversion` is a required field (instead of optional). This was an error in the Python documentation which was addressed recently.
https://docs.python.org/3.11/library/ast.html#ast.FormattedValue
https://github.com/python/cpython/pull/30467
* [Optional] We could add an enum for `FormattedValue.conversion`. The int values can be confusion on its own.

**Comment by rkhwaja** [comment]
The wrapt dependency needs to be ">=1.14" for python 3.11. See [changelog](https://wrapt.readthedocs.io/en/latest/changes.html#version-1-14-0)

**Comment by Pierre-Sassoulas** [comment]
@rkhwaja I think pip handle that, if pylint require wrapt >= 1.12 but python 3.11 require wrapt >= 1.14 then pip download >= 1.14. We should not change our lower bound, as we could imagine that wrapt >=1.14 is incompatible with python 3.7 and changing this would break pylint for python 3.7.

**Comment by rkhwaja** [comment]
You could add a dependency like "wrapt>=1.14,<2;python_version>='3.11'" and then both the old and the new python will work.

I don't know if you have other users than pylint but they would all just work too if you did it this way.

**Comment by Pierre-Sassoulas** [comment]
But is this required at all ? ``wrapt`` is the package that should handle the metadata about the pytho interpreters it supports and pip takes it into account.

**Comment by cdce8p** [comment]
> But is this required at all ? `wrapt` is the package that should handle the metadata about the pytho interpreters it supports and pip takes it into account.

Took me a moment to understand the issue. `wrap` doesn't pin a max supported version (which is the recommendation). Thus `pip` will happily install `1.12` even on python `3.11` if the dependency resolution requires it. However, only `1.14` is compatible. The options
* Add `wrapt>=1.14,<2;python_version>='3.11'` like @rkhwaja suggested
* Or just bump the min requirement to `1.14`. `1.14` is compatible with Python `>=3.5` so that wouldn't be an issue.
* End-users can always add the `wrapt>=1.14` constraint themselves. Although that won't fix existing environments.

**Comment by DanielNoord** [comment]
> * Or just bump the min requirement to `1.14`. `1.14` is compatible with Python `>=3.5` so that wouldn't be an issue.

See https://github.com/PyCQA/astroid/pull/1745
